### ISSUE TITLE
BufferOverflowException in single task graph implementation

### ISSUE THREAD

**Issue by otabuzzman** [otabuzzman/llm.java#1]
Exception raised after adding 4th layer:
```
java.nio.BufferOverflowException
        at java.base/java.nio.Buffer.nextPutIndex(Buffer.java:744)
        at java.base/java.nio.HeapByteBuffer.putInt(HeapByteBuffer.java:509)
        at tornado.runtime@1.0.8/uk.ac.manchester.tornado.runtime.tasks.TornadoTaskGraph.addInner(TornadoTaskGraph.java:671)
        at tornado.runtime@1.0.8/uk.ac.manchester.tornado.runtime.tasks.TornadoTaskGraph.addInner(TornadoTaskGraph.java:2188)
        at tornado.runtime@1.0.8/uk.ac.manchester.tornado.runtime.tasks.TornadoTaskGraph.addTask(TornadoTaskGraph.java:2256)
        at tornado.api@1.0.8/uk.ac.manchester.tornado.api.TaskGraph.addTask(TaskGraph.java:82)
        at com.otabuzzman.llmj.GPT2.forward(GPT2.java:940)
        at com.otabuzzman.llmj.TestGpt2.run(TestGpt2.java:122)
        at com.otabuzzman.llmj.TestGpt2.main(TestGpt2.java:207)
```

**Comment by otabuzzman** [comment]
Workaround: set `highLevelCode = new byte[20480]` in `./TornadoVM/tornado-runtime/.../runtime/tasks/TornadoTaskGraph.java`.
