### ISSUE TITLE
TornadoInternalError in single task graph implementation

### ISSUE THREAD

**Issue by otabuzzman** [otabuzzman/llm.java#2]
Exception raised after adding 11th layer:
```
Exception in thread "main" uk.ac.manchester.tornado.api.exceptions.TornadoInternalError: unimplemented: Tornado Graph resize not implemented yet.
        at tornado.api@1.0.8/uk.ac.manchester.tornado.api.exceptions.TornadoInternalError.unimplemented(TornadoInternalError.java:33)
        at tornado.runtime@1.0.8/uk.ac.manchester.tornado.runtime.graph.TornadoGraph.resize(TornadoGraph.java:83)
        at tornado.runtime@1.0.8/uk.ac.manchester.tornado.runtime.graph.TornadoGraph.add(TornadoGraph.java:57)
        at tornado.runtime@1.0.8/uk.ac.manchester.tornado.runtime.graph.TornadoGraphBuilder.buildGraph(TornadoGraphBuilder.java:118)
        at tornado.runtime@1.0.8/uk.ac.manchester.tornado.runtime.tasks.TornadoTaskGraph.compileGraphAndBuildVM(TornadoTaskGraph.java:703)
        at tornado.runtime@1.0.8/uk.ac.manchester.tornado.runtime.tasks.TornadoTaskGraph.compileComputeGraphToTornadoVMBytecode(TornadoTaskGraph.java:783)
        at tornado.runtime@1.0.8/uk.ac.manchester.tornado.runtime.tasks.TornadoTaskGraph.scheduleInner(TornadoTaskGraph.java:877)
        at tornado.runtime@1.0.8/uk.ac.manchester.tornado.runtime.tasks.TornadoTaskGraph.execute(TornadoTaskGraph.java:1412)
        at tornado.runtime@1.0.8/uk.ac.manchester.tornado.runtime.tasks.TornadoTaskGraph.execute(TornadoTaskGraph.java:1441)
        at tornado.api@1.0.8/uk.ac.manchester.tornado.api.TaskGraph.execute(TaskGraph.java:759)
        at tornado.api@1.0.8/uk.ac.manchester.tornado.api.ImmutableTaskGraph.execute(ImmutableTaskGraph.java:50)
        at tornado.api@1.0.8/uk.ac.manchester.tornado.api.TornadoExecutor.lambda$execute$0(TornadoExecutor.java:46)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at tornado.api@1.0.8/uk.ac.manchester.tornado.api.TornadoExecutor.execute(TornadoExecutor.java:46)
        at tornado.api@1.0.8/uk.ac.manchester.tornado.api.TornadoExecutionPlan.execute(TornadoExecutionPlan.java:154)
        at com.otabuzzman.llmj.GPT2.forward(GPT2.java:954)
        at com.otabuzzman.llmj.TestGpt2.run(TestGpt2.java:122)
        at com.otabuzzman.llmj.TestGpt2.main(TestGpt2.java:207)
```

**Comment by otabuzzman** [comment]
Workaround: set `INITIAL_SIZE = 2560` in `./TornadoVM/tornado-runtime/.../runtime/graph/TornadoGraph.java`.
